# Meshtastic2hass configuration file
# The device the Meshtastic device is connected to
device = "/dev/ttyUSB0"

[mqtt]
# MQTT broker host name or IP
host = "localhost"

# MQTT broker port
port = 1883

# MQTT broker user name
user = ""

# MQTT broker password
password = ""

# MQTT topic prefix
topic_prefix = "msh/2/json"

[meshtastic]
# Set of Meshtastic nodes short names to be includes in filter.
# Only these nodes will be forwarded to home assistant via MQTT topic, hence creating entities.
# Keep empty to forward all nodes.
# Receiving channels text from nodes is not filtered at all.
filter_nodes = []